export type ErrorCode =
  | "VALIDATION_ERROR"
  | "DOWNSTREAM_TIMEOUT"
  | "DOWNSTREAM_BAD_RESPONSE"
  | "DOWNSTREAM_UNAVAILABLE"
  | "INTERNAL_ERROR"
  | "NOT_FOUND"
  | "UNAUTHORIZED"
  | "FORBIDDEN";
